name: Build & Deploy Jupyter Book

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write         # required by actions/deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt && pip install jupyter-book
      - run: jupyter-book build . --keep-going
      # ✨ upload the generated site as an artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # ✨ publish the artifact to GitHub Pages
      - id: deployment
        uses: actions/deploy-pages@v4
