name: Build & Deploy Jupyter Book

on:
  push:
    branches: [main]

permissions:
  contents: read           # for checkout
  pages: write             # for deploy
  id-token: write          # required by deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1 ─ Checkout the repo
    - uses: actions/checkout@v4

    # 2 ─ Python env (same as before)
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3 ─ Install everything the notebooks import  ⟵  add matplotlib, scipy …
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # extra run-time deps used *inside* notebooks
        pip install matplotlib scipy ipywidgets

    # 4 ─ Build the Jupyter-Book (executes notebooks)
    - run: jupyter-book build . --keep-going

    # 5 ─ Copy raw notebooks (with their images) into the built site  ⟵  NEW
    - name: Copy notebooks to site folder
      run: |
        mkdir -p _build/html/notebooks
        cp -r notebooks/* _build/html/notebooks/

    # 6 ─ Upload the generated site
    - uses: actions/upload-pages-artifact@v3
      with:
        path: _build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
